### ISSUE TITLE
Setapp version.

### ISSUE THREAD

**Issue by huyphams** [chrisrenga/alfred-tableplus#1]
Hi, thanks for the wonderful open source! but we need to improve the script to compatible with the Setapp version 

```
/Library/Application Support/com.tinyapp.TablePlus-setapp/Data/Connections.plist;
/Library/Application Support/com.tinyapp.TablePlus-setapp/Data/ConnectionGroups.plist
```
We can improve the script by checking the existence of the files and fallback to the default location. Let me know if you need anything else.

**Comment by chrisrenga** [comment]
Thanks! [0.0.2](https://github.com/chrisrenga/alfred-tableplus/releases/tag/0.0.2)
