### ISSUE TITLE
Database selection after connection selected

### ISSUE THREAD

**Issue by royduin** [chrisrenga/alfred-tableplus#3]
It would be nice to have the possibility to select a database after selecting the connection. For example: `tp connection database`

**Comment by chrisrenga** [comment]
Hi @royduin, 
actually thought about this the other day but, as much as I know, TablePlus only allows you to use connection id's to launch the application. The id's are based on your existing connection configuration so I wouldn't be able to change the database name for a given connection before opening the application.

There is also not the option of getting all the database names as they are not stored anywhere. A separate connection to the DB would need to be established and that would require having all the DB and SSH connection values (user, pw, private keys...).

Feel free to suggest something if you have a better idea to get this working.

Thanks,
